DROP TABLE IF EXISTS User
DROP TABLE IF EXISTS Business
DROP TABLE IF EXISTS Item
DROP TABLE IF EXISTS Image
DROP TABLE IF EXISTS Client
DROP TABLE IF EXISTS ClientOrder
DROP TABLE IF EXISTS OrderItem
